"""
Django settings for CleanSoundStudio project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    env_file = Path(__file__).resolve().parent.parent / 'docker-file' / '.env'
    if env_file.exists():
        load_dotenv(env_file)
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-jzfrxv-pe_#sgxnx2k5u4urb$!j*+$_9w4m_y0&5#t8bi)26(9')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# TinyMCE API Key from environment
TINYMCE_API_KEY = os.getenv('TINYMCE_API_KEY', '')

def _env_list(name, default_list):
    raw_value = os.getenv(name)
    if raw_value:
        return [item.strip() for item in raw_value.split(',') if item.strip()]
    return default_list


# Ngrok Configuration
ALLOWED_HOSTS = _env_list(
    'DJANGO_ALLOWED_HOSTS',
    [
        'localhost',
        '127.0.0.1',
        '0.0.0.0',
        'web',
    ],
)

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = _env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'Article',
    'DashboardAdmin',
    'tailwind',
]

MIDDLEWARE = [
    'Article.middleware.NgrokHostMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Article.middleware.LanguageMiddleware',
]

ROOT_URLCONF = 'CleanSoundStudio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Article.context_processors.language_context',
                'DashboardAdmin.context_processors.tinymce_api_key',
            ],
        },
    },
]

WSGI_APPLICATION = 'CleanSoundStudio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'db_dashboard_admin'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL prefix for static files
STATIC_URL = '/static/'

# Directory for project-level static files (during development)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directory where `collectstatic` will gather files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ["127.0.0.1"]


# Arahkan user yang belum login ke view 'login' milik aplikasi DashboardAdmin
LOGIN_URL = 'DashboardAdmin:login'

# CORS
# Untuk development cepat Anda bisa mengizinkan semua origin.
# Untuk produksi, ganti dengan `CORS_ALLOWED_ORIGINS` yang spesifik.
CORS_ALLOW_ALL_ORIGINS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
