# Generated by Django 5.2.8 on 2025-12-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0004_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
