# Generated by Django 5.2.8 on 2025-12-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0005_sitesetting_youtube_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ad_down',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ad_left',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ad_right',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
