# Generated by Django 5.2.8 on 2025-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0006_sitesetting_ad_down_sitesetting_ad_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='translate_api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='translate_api_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
