# Generated by Django 5.2.8 on 2026-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0007_sitesetting_translate_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='vote_link',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
