# Generated by Django 5.2.8 on 2026-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0008_sitesetting_vote_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ad_top',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
