# Generated by Django 5.2.8 on 2026-02-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0012_articletranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
