from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	dependencies = [
		('DashboardAdmin', '0013_increase_translation_title_length'),
	]

	operations = [
		migrations.CreateModel(
			name='SiteSettingTranslation',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('lang', models.CharField(choices=[('id', 'Indonesian'), ('en', 'English'), ('ja', 'Japanese')], max_length=5)),
				('youtube_desc', models.TextField(blank=True, default='')),
				('source_hash', models.CharField(blank=True, default='', max_length=64)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='DashboardAdmin.sitesetting')),
			],
			options={},
		),
		migrations.AddConstraint(
			model_name='sitesettingtranslation',
			constraint=models.UniqueConstraint(fields=('setting', 'lang'), name='unique_sitesetting_lang'),
		),
	]# Generated by Django 5.2.8 on 2026-02-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0013_increase_translation_title_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettingTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('id', 'Indonesian'), ('en', 'English'), ('ja', 'Japanese')], max_length=5)),
                ('youtube_desc', models.TextField(blank=True, default='')),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='DashboardAdmin.sitesetting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('setting', 'lang'), name='unique_sitesetting_lang')],
            },
        ),
    ]
